// Auto-generated from 03_models_and_messages.ipynb
// Do not edit manually -- regenerate with nb2typ.py
#import "../../template.typ": *
#import "../../metadata.typ": *

#chapter(3, "Models and the Message System")

Learn how to configure different LLM models in LangChain v1 and structure conversations with message types.


== Learning Objectives

- Understand the LangChain v1 model initialization methods (`init_chat_model`, `ChatOpenAI`)
- Learn the three call patterns: `invoke()`, `stream()`, and `batch()`
- Understand message types such as `SystemMessage`, `HumanMessage`, `AIMessage`, and `ToolMessage`
- Learn how to construct multimodal messages (image input)


== 3.1 Environment Setup

Load API keys from `.env` and initialize the model through OpenAI.


#code-block(`````python
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI

load_dotenv(override=True)

# Initialize the model with OpenAI
model = ChatOpenAI(
    model="gpt-5.4",
)

print("Model initialized:", model.model_name)
`````)

== 3.2 Comparing Model Providers

LangChain v1 can initialize models from many providers through the unified `init_chat_model()` API.

#table(
  columns: 4,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[Provider],
  text(weight: "bold")[Model String Format],
  text(weight: "bold")[Required Package],
  text(weight: "bold")[Environment Variable],
  [OpenAI],
  [`"openai:gpt-5"`],
  [`langchain-openai`],
  [`OPENAI_API_KEY`],
  [Anthropic],
  [`"anthropic:claude-sonnet-4-6"`],
  [`langchain-anthropic`],
  [`ANTHROPIC_API_KEY`],
  [Google],
  [`"google:gemini-2.5-flash-lite"`],
  [`langchain-google-genai`],
  [`GOOGLE_API_KEY`],
  [AWS Bedrock],
  [`"bedrock:anthropic.claude-v3"`],
  [`langchain-aws`],
  [AWS credentials],
  [Azure],
  [`"azure:gpt-4o"`],
  [`langchain-openai`],
  [`AZURE_OPENAI_API_KEY`],
  [Ollama],
  [`"ollama:llama3"`],
  [`langchain-ollama`],
  [(local runtime)],
)

#note-box[_Note:_ When using OpenAI, you can set `base_url` and `api_key` directly on `ChatOpenAI` to connect to OpenAI-style services such as vLLM, LM Studio, or Ollama.]


== 3.3 Using `init_chat_model()`

`init_chat_model()` is the unified model initialization helper introduced in LangChain v1.
If the provider-specific package is installed, you can create a model with a single string.

When you are using OpenAI directly, `ChatOpenAI` is usually the more straightforward option.


== 3.4 `invoke()`, `stream()`, and `batch()` Patterns

Every LangChain v1 model supports three calling patterns:

#table(
  columns: 3,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[Method],
  text(weight: "bold")[Description],
  text(weight: "bold")[Return Type],
  [`invoke()`],
  [One response for one input],
  [`AIMessage`],
  [`stream()`],
  [Token-by-token streaming response],
  [`Iterator[AIMessageChunk]`],
  [`batch()`],
  [Handles multiple inputs at the same time],
  [`List[AIMessage]`],
)


== 3.5 Message Types

LangChain v1's message system clearly separates the roles inside a conversation:

#table(
  columns: 3,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[Message Type],
  text(weight: "bold")[Role],
  text(weight: "bold")[Description],
  [`SystemMessage`],
  [System],
  [A system prompt that defines how the model should behave],
  [`HumanMessage`],
  [User],
  [A message entered by the user],
  [`AIMessage`],
  [AI],
  [A response generated by the model],
  [`ToolMessage`],
  [Tool],
  [A message that passes a tool result back to the model],
)

If you build a list of messages and pass it into `model.invoke()`, you can preserve the conversation context across turns.


== 3.6 Multimodal Messages (Image Input)

In LangChain v1, you can send text and images together in the `content` of a `HumanMessage`.
Images can be passed as URLs or as base64-encoded content, and this works only with models that support vision input.

#code-block(`````python
content = [
    {"type": "text", "text": "Description text"},
    {"type": "image_url", "image_url": {"url": "IMAGE_URL"}},
]
`````)


== 3.7 Standard Output Format — `output_version="v1"`

Starting from LangChain v1, every provider can emit a unified _content blocks_ serialization. Set `init_chat_model("openai:gpt-5.4", output_version="v1")` or the env var `LC_OUTPUT_VERSION="v1"`, and `AIMessage.content_blocks` will give you text, tool calls, reasoning, thinking, and citations in a single schema.

#code-block(`````python
import os
from langchain.chat_models import init_chat_model

os.environ["LC_OUTPUT_VERSION"] = "v1"

model = init_chat_model("openai:gpt-5.4", output_version="v1")
result = model.invoke("Describe LangChain v1 in one sentence.")

for block in result.content_blocks:
    print(block["type"], "→", block.get("text", block))
`````)

Streaming uses the same shape. Read partial blocks from `chunk.content_blocks` and map them to your UI.

#code-block(`````python
for chunk in model.stream("Explain multimodal input."):
    for block in chunk.content_blocks:
        if block["type"] == "text":
            print(block["text"], end="")
`````)

#tip-box[`output_version="v1"` is the recommended setting for absorbing provider differences. Legacy code that depends on the string `result.content` still works in `v0`, but new projects should use v1.]


== 3.8 Tracking Token Usage — `UsageMetadataCallbackHandler`

For multi-step agent runs, aggregate token usage with a callback handler. Pass `UsageMetadataCallbackHandler` through `config={"callbacks": [...]}`, and `input_tokens` / `output_tokens` / `total_tokens` accumulate across every model call.

#code-block(`````python
from langchain_core.callbacks import UsageMetadataCallbackHandler

cb = UsageMetadataCallbackHandler()
result = agent.invoke(
    {"messages": [{"role": "user", "content": "What is 15 * 27 + 3?"}]},
    config={"callbacks": [cb]},
)

print(cb.usage_metadata)
# {'gpt-5.4': {'input_tokens': 312, 'output_tokens': 48, 'total_tokens': 360, ...}}
`````)


== 3.9 Runtime Config — Per-Invocation Options

The `config=` argument on `invoke()` / `stream()` carries execution metadata for a single call. You can set the LangSmith trace name, tags, metadata, and concurrency limits for tools and sub-agents all at once.

#code-block(`````python
result = agent.invoke(
    {"messages": [{"role": "user", "content": "..."}]},
    config={
        "run_name": "monthly-report",
        "tags": ["batch-2025-05", "finance"],
        "metadata": {"user_id": "u-1234", "tenant": "acme"},
        "max_concurrency": 5,
    },
)
`````)

#tip-box[`run_name`, `tags`, and `metadata` flow into LangSmith and become filter/search keys in the UI. `max_concurrency` caps the parallel tool and sub-agent calls inside one graph execution.]


== 3.10 Connection Resilience — `max_retries` / `timeout`

In production, you have to ride out temporary outages from OpenAI, Anthropic, and other providers. Pass `max_retries` and `timeout` to `init_chat_model()` or `ChatOpenAI()`, and LangChain will retry with exponential backoff.

#code-block(`````python
from langchain.chat_models import init_chat_model

model = init_chat_model(
    "openai:gpt-5.4",
    max_retries=15,   # default is 6 — raise it for resilience
    timeout=120,      # seconds, for long responses
)
`````)

#tip-box[Retries fire on 5xx errors, connection failures, and `429 Too Many Requests`. Client errors like 422 are not retried. Setting the limit too high amplifies cost and latency, so most teams keep it in the 10–20 range.]


== 3.11 Prompt Caching — Implicit vs Explicit

When you reuse a long system prompt or RAG context, prompt caching can cut input token costs sharply.

- _Implicit caching_: the provider detects an identical prefix automatically. OpenAI `gpt-5.4` enables this for prefixes of 1024 tokens or more.
- _Explicit caching_: Anthropic uses `prompt_cache_key` (or a `cache_control` block) to mark cache keys. In LangChain you pass it via `model_kwargs={"prompt_cache_key": "..."}`.

#code-block(`````python
from langchain_anthropic import ChatAnthropic

model = ChatAnthropic(
    model="claude-sonnet-4-6",
    model_kwargs={"prompt_cache_key": "system-v3"},
)
`````)

#tip-box[On cache hits, `usage_metadata.input_tokens_details` reports `cache_read` and `cache_creation` separately. Track cache hit rate as an ops metric with `UsageMetadataCallbackHandler`.]


== 3.12 Summary

Here is a summary of the main ideas from this notebook.

#table(
  columns: 2,
  align: left,
  stroke: 0.5pt + luma(200),
  inset: 8pt,
  fill: (_, row) => if row == 0 { rgb("#E0F2F3") } else if calc.odd(row) { luma(248) } else { white },
  text(weight: "bold")[Item],
  text(weight: "bold")[Description],
  [`init_chat_model()`],
  [Initializes models through a unified provider string],
  [`ChatOpenAI(base_url=...)`],
  [Uses OpenAI or another custom endpoint],
  [`invoke()`],
  [Single input → single response],
  [`stream()`],
  [Token-level streaming response],
  [`batch()`],
  [Handles multiple inputs at once],
  [`SystemMessage`],
  [Sets system instructions],
  [`HumanMessage`],
  [Represents user input],
  [`AIMessage`],
  [Represents an AI response (for conversation history)],
  [`ToolMessage`],
  [Carries tool execution results],
  [Multimodal message],
  [Sends text and images together in `content`],
)

=== Next Steps
→ _#link("./04_tools_and_structured_output.ipynb")[04_tools_and_structured_output.ipynb]_: Learn about tools and structured output.

